version: '3.8'

services:
  my-zoo-app:
    build: .
    container_name: my-zoo-app
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    restart: always
    volumes:
      - .:/opt