apiVersion: v1
kind: Service
metadata:
  name: zoo-app-service
  labels:
    app: zoo-app
spec:
  type: NodePort
  selector:
    app: zoo-app
  ports:
    - port: 80           # פורט הגישה ל-Service
      targetPort: 8000   # פורט שבו האפליקציה מאזינה בפודים
      nodePort: 30080    # הפורט החיצוני לגישה מהדפדפן